version: '3'
services:
    mqtt:
        image: eclipse-mosquitto:latest
        ports:
            - "1883:1883"

    influxdb:
        image: influxdb:latest
        ports:
            - "8086:8086"
        volumes:
            # Data persistence
            # sudo mkdir -p /srv/docker/influxdb/data
            - /srv/docker/influxdb/data:/var/lib/influxdb

    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        volumes:
            # Data persistence
            # sudo mkdir -p /srv/docker/grafana/data; sudo chown 472:472 /srv/docker/grafana/data
            - /srv/docker/grafana/data:/var/lib/grafana

    telegraf:
        image: telegraf:latest
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
