mqtt:
  image: eclipse-mosquitto:latest
  container_name: mqtt
  ports:
    - "1883:1883"

influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - /srv/docker/influxdb/data:/var/lib/influxdb

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data; sudo chown 472:472 /srv/docker/grafana/data
    - /srv/docker/grafana/data:/var/lib/grafana

telegraf:
  image: telegraf:latest
  container_name: telegraf
  links:
    - influxdb
    - mqtt
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
